name: Update cast-database.json

on:
  repository_dispatch:
    types: [update-cast-database-json]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Write cast-database.json
        run: |
          echo '${{ github.event.client_payload.json }}' > cast-database.json

      - name: Commit and push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "flickmint-cast-bot@users.noreply.github.com"
          git add cast-database.json
          git commit -m "chore: update cast-database.json via GitHub Action" || echo "No changes to commit"
          git push
